apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-lens-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-lens-service
  template:
    metadata:
      labels:
        app: summary-lens-service
    spec:
      containers:
      - name: summary-lens-python
        image: gghcr.io/gravitate-health/summary-lens-service:latest
        imagePullPolicy: Always
        env:
        - name: FHIR_EPI_URL
          value: "http://fhir-server-epi:8080/epi/api/fhir"
        - name: FHIR_IPS_URL
          value: "http://fhir-server-ips:8080/ips/api/fhir"
        - name: MODEL_URL
          value: "http://tinman.lst:11434"
        - name: OPENAI_KEY
          value: ""
        - name: GROQ_API_KEY
          value: ""
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
status: {}
