apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary-lens-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summary-lens-service
  template:
    metadata:
      labels:
        app: summary-lens-service
    spec:
      containers:
      - name: summary-lens-service
        image: ghcr.io/gravitate-health/summary-lens-service:v0.13.0
        imagePullPolicy: Always
        env:
        - name: FHIR_EPI_URL
          value: "http://fhir-server-epi:8080/api/fhir"
        - name: FHIR_IPS_URL
          value: "http://fhir-server-ips:8080/api/fhir"
        - name: MODEL_URL
          value: "https://ollama.lst.tfo.upm.es"
        - name: OPENAI_KEY
          value: ""
        - name: GROQ_API_KEY
          value: ""
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
status: {}
